title = "Gunardi"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "en-us"
theme = ["ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
metaDescription = ""
googleAnalytics = ""
enableRobotsTXT = true

canonifyURLs = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Gunardi Ali"
  favicon = ""
  site_logo = ""
  TIMEZONE = "Europe/Berlin"
  date_format = "2. January 2006"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[params.ananke_socials]
    [params.ananke_socials.medium]
      name = "medium"
      url = "https://medium.com/@gunardilin"
      color = "#008cff"
    [params.ananke_socials.github]
      name = "github"
      url = "https://github.com/gunardilin"
      color = "#008cff"
    [params.ananke_socials.linkedin]
      name = "linkedin"
      url = "http://www.linkedin.com/in/gunardi-ali"
      color = "#008cff"
    [params.ananke_socials.Resume]
      name = "resume"
      url = "/docs/Lebenslauf.pdf"
      label = "Resume"
      color = "#008cff"
  
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 20

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 40